### ISSUE TITLE
[TS2503] Should we override `Animated` to be a TS `namespace`?

### ISSUE THREAD

**Issue by alloy** [microsoft/flow2dts#11]
Currently in DT `Animated` is [defined as a namespace](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/71fda87ba0f5beca739984223dd5544499757d97/types/react-native/index.d.ts#L8737), whereas it's a plain object in the Flow types.

```ts
import { Animated } from "react-native"
const value: Animated.Value = new Animated.Value(42)
```

**Comment by alloy** [comment]
I’m on the fence as to what to do here.

**Comment by alloy** [comment]
I recall that @TheSavior previously had mentioned that RN core is open to accepting patches to change code to use ES6 syntax, but that they simply hadn’t had a strong need to do so yet. Perhaps the `Animated` APIs would be a good case to change upstream so that we don’t need to do any real conversions, but that means that for the time being we should perform that change in the TS typings with an override.

**Comment by TheSavior** [comment]
What would you propose the change to the upstream code looks like?

**Comment by alloy** [comment]
I decided to fix it in TS instead, seeing as namespaces are a TS only thing. https://github.com/microsoft/flow2dts/commit/d385982e8b7a8d4d0cbf43bfd5859ba5de096f12
