### ISSUE TITLE
Don't store classes in intermediate variables

### ISSUE THREAD

**Issue by alloy** [microsoft/flow2dts#18]
Consider the following examples:

### [Libraries/Animated/src/nodes/AnimatedValue.js.flow](https://github.com/microsoft/flow2dts/blob/36cbc9ebe6462820fed1ea70cdf74299d78d0e85/workbench/react-native/v0.63.3/inputs/Libraries/Animated/src/nodes/AnimatedValue.js.flow)

```js
declare class AnimatedValue {}
declare module.exports: typeof AnimatedValue;
```

### [Libraries/Animated/src/AnimatedMock.js.flow](https://github.com/microsoft/flow2dts/blob/36cbc9ebe6462820fed1ea70cdf74299d78d0e85/workbench/react-native/v0.63.3/inputs/Libraries/Animated/src/AnimatedMock.js.flow)

```js
declare var AnimatedValue: typeof $7;
const $7 = require("./nodes/AnimatedValue");

declare var someFunction: (
  value: AnimatedValue,
) => void;
```

### Libraries/Animated/src/nodes/AnimatedValue.d.ts

```ts
declare class AnimatedValue {}
default export AnimatedValue;
```

### Libraries/Animated/src/AnimatedMock.d.ts

```ts
import AnimatedValue from "./nodes/AnimatedValue";

declare var someFunction: (
  value: AnimatedValue,
) => void;
```

**Comment by ZihanChen-MSFT** [comment]
Fixed by doing resolving and deleting intermediate variables
