### ISSUE TITLE
Generate a hint file for identifiers for workbench input

### ISSUE THREAD

**Issue by alloy** [microsoft/flow2dts#9]
As https://github.com/alloy/flow2dts/issues/24 said, if we know whether a identifier is a class, a type or a value, it would help us get rid of generating `$TypeOf<typeof T>` to make the code correct.

A new package is expected as a separate pass to generate this hint file. If the input is changed, execute this package to generate new hint files. Once hint files are ready, our transpiler can be updated to leverage on these files.

**Comment by alloy** [comment]
d0d0230 have called `flow get-def` on all import specifiers. But for code like

```flow
import * as React from "react"
```

`flow get-def` is not able to track the `React` here, but it can track React.**Node** later.

The script needs to be updated to first collect or `ImportNamespaceSpecifier`, and then track all `QualifiedTypeIdentifier` after imported namespaces.

**Comment by ZihanChen-MSFT** [comment]
Search for `\$TypeOf<typeof \w+(?!\$f2tTypeof)>` in vscode in `workbench\react-native\v0.63.3`

There are generally two kinds of `$TypeOf` with a few others:
- reference a local symbol
- reference something like `React.ElementRef`

The next step is to resolve local symbols by calling `getBinding`.

**Comment by ZihanChen-MSFT** [comment]
Fixed by c73639c
